name = "multi-region-address-generator"
main = "src/index.js"
compatibility_date = "2026-03-14"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "addygen.banez.de"
custom_domain = true

[[kv_namespaces]]
binding = "ADDRESS_CACHE"
id = "b5cb2f5a22b449ceb0582adfce0c6a74"
